version: '3'

services:
  github_auto_search_web:
    container_name: github_auto_search_web
    image: nginx:mainline-alpine
    ports:
      - 80:80
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - github_auto_search_app

  github_auto_search_app:
    container_name: github_auto_search_app
    build: ./php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - github_auto_search_db

  github_auto_search_db:
    container_name: github_auto_search_db
    image: mysql:5.7
    ports:
      - 3306:3306
    tty: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ='Asia/Tokyo'
    volumes:
      - ./mysql:/etc/mysql/mysql.conf.d
      - github_auto_search_data:/var/lib/mysql

  github_auto_search_redis:
    container_name: github_auto_search_redis
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  github_auto_search_data:
